spring:
  profiles:
    active: dev
  ########################################################
  ### 数据库配置
  ########################################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starrynight?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  ########################################################
  ### JPA配置
  ########################################################
  jpa:
    database: mysql
    show-sql: true
    # 不加这句则默认为myisam引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        # 命名策略
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  ########################################################
  ### 热部署生效
  ########################################################
  devtools:
    restart:
      enabled: true
  ########################################################
  ###THYMELEAF (ThymeleafAutoConfiguration)
  ########################################################
  mvc:
    #view:
    # 静态文件请求匹配方式
    static-path-pattern: /**
  thymeleaf:
    # 定位模板的目录x
    prefix: classpath:/templates/
    # 给返回的页面添加后缀名
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  # 修改默认的静态寻址资源目录
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

